/**
 * API-related types and interfaces
 */

export interface ApiResponse<T = unknown> {
  data?: T
  error?: ApiError
  success: boolean
}

export interface ApiError {
  message: string
  code: string
  details?: Record<string, unknown>
}

export interface PaginationParams {
  page: number
  limit: number
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
}

export interface PaginatedResponse<T> {
  data: T[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

// GraphQL-specific types
export interface GraphQLError {
  message: string
  path?: string[]
  extensions?: Record<string, unknown>
}

// Auth GraphQL Response Types
export interface LoginResponse {
  login: {
    success: boolean
    message: string
    data: {
      accessToken: string
      refreshToken: string
      user: {
        id: string
        name: string
        email: string
        isAdmin: boolean
        emailVerified: boolean
      }
    }
  }
}

export interface RefreshTokenResponse {
  refreshToken: {
    success: boolean
    message: string
    data: {
      accessToken: string
      refreshToken: string
    }
  }
}

export interface MeResponse {
  me: {
    success: boolean
    message: string
    data: {
      id: string
      name: string
      email: string
      isAdmin: boolean
      emailVerified: boolean
      createdAt: string
      updatedAt: string
    }
  }
}

export interface CreateUserResponse {
  createUser: {
    success: boolean
    message?: string
    data?: {
      id: string
      email: string
    }
  }
}

export interface LogoutResponse {
  logout: {
    success: boolean
    message: string
  }
}

export interface ForgotPasswordResponse {
  forgotPassword: {
    success: boolean
    message: string
  }
}

export interface VerifyEmailResponse {
  verifyEmail: {
    success: boolean
    message?: string
  }
}

// Tenant GraphQL Response Types
export interface Tenant {
  id: string
  uuid?: string
  name: string
  slug: string
  domain?: string
  isNameAutoGenerated?: boolean
  createdBy?: string
  createdAt: string
  updatedAt?: string
}

export interface TenantsData {
  tenants: Tenant[]
  total: number
  page: number
  perPage: number
}

export interface TenantsResponse {
  tenants: {
    success: boolean
    message: string
    data: TenantsData
  }
}

export interface TenantResponse {
  tenant: {
    success: boolean
    message: string
    data: Tenant
  }
}

export interface CreateTenantResponse {
  createTenant: {
    success: boolean
    message: string
    data: Tenant
  }
}

export interface UpdateTenantResponse {
  updateTenant: {
    success: boolean
    message: string
    data: Tenant
  }
}

export interface DeleteTenantResponse {
  deleteTenant: {
    success: boolean
    message: string
  }
}

// Tenant Users Types
export interface TenantUser {
  id: string
  name: string
  email: string
  role: string
  isDefault: boolean
  createdAt: string
}

export interface TenantUsersResponse {
  tenantUsers: {
    success: boolean
    message: string
    data: TenantUser[]
  }
}

export interface AddUserToTenantResponse {
  addUserToTenant: {
    success: boolean
    message: string
    data: {
      userId: string
      tenantId: string
      role: string
      isDefault: boolean
    }
  }
}

export interface RemoveUserFromTenantResponse {
  removeUserFromTenant: {
    success: boolean
    message: string
  }
}

export interface UpdateUserRoleResponse {
  updateUserRole: {
    success: boolean
    message: string
  }
}

// User Detail Types
export interface UserDetail {
  id: string
  name: string
  email: string
  publicName?: string
  isAdmin: boolean
  isBlocked: boolean
  phoneNumber?: string
  position?: string
  emailVerified: boolean
  emailVerifiedAt?: number
  lastLoginAt?: number
  createdAt: number
  updatedAt: number
}

export interface UserByIdResponse {
  user: {
    success: boolean
    message: string
    data: UserDetail
  }
}
