// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_GetProductByID_FullMethodName      = "/product.ProductService/GetProductByID"
	ProductService_GetProductBySlug_FullMethodName    = "/product.ProductService/GetProductBySlug"
	ProductService_CreateProduct_FullMethodName       = "/product.ProductService/CreateProduct"
	ProductService_UpdateProduct_FullMethodName       = "/product.ProductService/UpdateProduct"
	ProductService_DeleteProduct_FullMethodName       = "/product.ProductService/DeleteProduct"
	ProductService_GetAllProducts_FullMethodName      = "/product.ProductService/GetAllProducts"
	ProductService_GetPlanByID_FullMethodName         = "/product.ProductService/GetPlanByID"
	ProductService_GetPlanBySlug_FullMethodName       = "/product.ProductService/GetPlanBySlug"
	ProductService_GetPlansByProduct_FullMethodName   = "/product.ProductService/GetPlansByProduct"
	ProductService_CreatePlan_FullMethodName          = "/product.ProductService/CreatePlan"
	ProductService_UpdatePlan_FullMethodName          = "/product.ProductService/UpdatePlan"
	ProductService_DeletePlan_FullMethodName          = "/product.ProductService/DeletePlan"
	ProductService_GetAllPlans_FullMethodName         = "/product.ProductService/GetAllPlans"
	ProductService_GetPlanPrice_FullMethodName        = "/product.ProductService/GetPlanPrice"
	ProductService_GetPlanPricesByPlan_FullMethodName = "/product.ProductService/GetPlanPricesByPlan"
	ProductService_CreatePlanPrice_FullMethodName     = "/product.ProductService/CreatePlanPrice"
	ProductService_UpdatePlanPrice_FullMethodName     = "/product.ProductService/UpdatePlanPrice"
	ProductService_DeletePlanPrice_FullMethodName     = "/product.ProductService/DeletePlanPrice"
	ProductService_GetPlanMeterByID_FullMethodName    = "/product.ProductService/GetPlanMeterByID"
	ProductService_GetAllPlanMeters_FullMethodName    = "/product.ProductService/GetAllPlanMeters"
	ProductService_CreatePlanMeter_FullMethodName     = "/product.ProductService/CreatePlanMeter"
	ProductService_UpdatePlanMeter_FullMethodName     = "/product.ProductService/UpdatePlanMeter"
	ProductService_DeletePlanMeter_FullMethodName     = "/product.ProductService/DeletePlanMeter"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	// Product operations
	GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error)
	GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*GetProductBySlugResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error)
	// Plan operations
	GetPlanByID(ctx context.Context, in *GetPlanByIDRequest, opts ...grpc.CallOption) (*GetPlanByIDResponse, error)
	GetPlanBySlug(ctx context.Context, in *GetPlanBySlugRequest, opts ...grpc.CallOption) (*GetPlanBySlugResponse, error)
	GetPlansByProduct(ctx context.Context, in *GetPlansByProductRequest, opts ...grpc.CallOption) (*GetPlansByProductResponse, error)
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*UpdatePlanResponse, error)
	DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...grpc.CallOption) (*DeletePlanResponse, error)
	GetAllPlans(ctx context.Context, in *GetAllPlansRequest, opts ...grpc.CallOption) (*GetAllPlansResponse, error)
	// Plan Price operations
	GetPlanPrice(ctx context.Context, in *GetPlanPriceRequest, opts ...grpc.CallOption) (*GetPlanPriceResponse, error)
	GetPlanPricesByPlan(ctx context.Context, in *GetPlanPricesByPlanRequest, opts ...grpc.CallOption) (*GetPlanPricesByPlanResponse, error)
	CreatePlanPrice(ctx context.Context, in *CreatePlanPriceRequest, opts ...grpc.CallOption) (*CreatePlanPriceResponse, error)
	UpdatePlanPrice(ctx context.Context, in *UpdatePlanPriceRequest, opts ...grpc.CallOption) (*UpdatePlanPriceResponse, error)
	DeletePlanPrice(ctx context.Context, in *DeletePlanPriceRequest, opts ...grpc.CallOption) (*DeletePlanPriceResponse, error)
	// Plan Meter operations
	GetPlanMeterByID(ctx context.Context, in *GetPlanMeterByIDRequest, opts ...grpc.CallOption) (*GetPlanMeterByIDResponse, error)
	GetAllPlanMeters(ctx context.Context, in *GetAllPlanMetersRequest, opts ...grpc.CallOption) (*GetAllPlanMetersResponse, error)
	CreatePlanMeter(ctx context.Context, in *CreatePlanMeterRequest, opts ...grpc.CallOption) (*CreatePlanMeterResponse, error)
	UpdatePlanMeter(ctx context.Context, in *UpdatePlanMeterRequest, opts ...grpc.CallOption) (*UpdatePlanMeterResponse, error)
	DeletePlanMeter(ctx context.Context, in *DeletePlanMeterRequest, opts ...grpc.CallOption) (*DeletePlanMeterResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductByIDResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*GetProductBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductBySlugResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, ProductService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllProductsResponse)
	err := c.cc.Invoke(ctx, ProductService_GetAllProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlanByID(ctx context.Context, in *GetPlanByIDRequest, opts ...grpc.CallOption) (*GetPlanByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanByIDResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlanByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlanBySlug(ctx context.Context, in *GetPlanBySlugRequest, opts ...grpc.CallOption) (*GetPlanBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanBySlugResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlanBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlansByProduct(ctx context.Context, in *GetPlansByProductRequest, opts ...grpc.CallOption) (*GetPlansByProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlansByProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlansByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanResponse)
	err := c.cc.Invoke(ctx, ProductService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*UpdatePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlanResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...grpc.CallOption) (*DeletePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlanResponse)
	err := c.cc.Invoke(ctx, ProductService_DeletePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAllPlans(ctx context.Context, in *GetAllPlansRequest, opts ...grpc.CallOption) (*GetAllPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPlansResponse)
	err := c.cc.Invoke(ctx, ProductService_GetAllPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlanPrice(ctx context.Context, in *GetPlanPriceRequest, opts ...grpc.CallOption) (*GetPlanPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanPriceResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlanPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlanPricesByPlan(ctx context.Context, in *GetPlanPricesByPlanRequest, opts ...grpc.CallOption) (*GetPlanPricesByPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanPricesByPlanResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlanPricesByPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreatePlanPrice(ctx context.Context, in *CreatePlanPriceRequest, opts ...grpc.CallOption) (*CreatePlanPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanPriceResponse)
	err := c.cc.Invoke(ctx, ProductService_CreatePlanPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdatePlanPrice(ctx context.Context, in *UpdatePlanPriceRequest, opts ...grpc.CallOption) (*UpdatePlanPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlanPriceResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdatePlanPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeletePlanPrice(ctx context.Context, in *DeletePlanPriceRequest, opts ...grpc.CallOption) (*DeletePlanPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlanPriceResponse)
	err := c.cc.Invoke(ctx, ProductService_DeletePlanPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPlanMeterByID(ctx context.Context, in *GetPlanMeterByIDRequest, opts ...grpc.CallOption) (*GetPlanMeterByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanMeterByIDResponse)
	err := c.cc.Invoke(ctx, ProductService_GetPlanMeterByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAllPlanMeters(ctx context.Context, in *GetAllPlanMetersRequest, opts ...grpc.CallOption) (*GetAllPlanMetersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPlanMetersResponse)
	err := c.cc.Invoke(ctx, ProductService_GetAllPlanMeters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreatePlanMeter(ctx context.Context, in *CreatePlanMeterRequest, opts ...grpc.CallOption) (*CreatePlanMeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanMeterResponse)
	err := c.cc.Invoke(ctx, ProductService_CreatePlanMeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdatePlanMeter(ctx context.Context, in *UpdatePlanMeterRequest, opts ...grpc.CallOption) (*UpdatePlanMeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlanMeterResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdatePlanMeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeletePlanMeter(ctx context.Context, in *DeletePlanMeterRequest, opts ...grpc.CallOption) (*DeletePlanMeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlanMeterResponse)
	err := c.cc.Invoke(ctx, ProductService_DeletePlanMeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	// Product operations
	GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error)
	GetProductBySlug(context.Context, *GetProductBySlugRequest) (*GetProductBySlugResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	GetAllProducts(context.Context, *GetAllProductsRequest) (*GetAllProductsResponse, error)
	// Plan operations
	GetPlanByID(context.Context, *GetPlanByIDRequest) (*GetPlanByIDResponse, error)
	GetPlanBySlug(context.Context, *GetPlanBySlugRequest) (*GetPlanBySlugResponse, error)
	GetPlansByProduct(context.Context, *GetPlansByProductRequest) (*GetPlansByProductResponse, error)
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error)
	UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanResponse, error)
	DeletePlan(context.Context, *DeletePlanRequest) (*DeletePlanResponse, error)
	GetAllPlans(context.Context, *GetAllPlansRequest) (*GetAllPlansResponse, error)
	// Plan Price operations
	GetPlanPrice(context.Context, *GetPlanPriceRequest) (*GetPlanPriceResponse, error)
	GetPlanPricesByPlan(context.Context, *GetPlanPricesByPlanRequest) (*GetPlanPricesByPlanResponse, error)
	CreatePlanPrice(context.Context, *CreatePlanPriceRequest) (*CreatePlanPriceResponse, error)
	UpdatePlanPrice(context.Context, *UpdatePlanPriceRequest) (*UpdatePlanPriceResponse, error)
	DeletePlanPrice(context.Context, *DeletePlanPriceRequest) (*DeletePlanPriceResponse, error)
	// Plan Meter operations
	GetPlanMeterByID(context.Context, *GetPlanMeterByIDRequest) (*GetPlanMeterByIDResponse, error)
	GetAllPlanMeters(context.Context, *GetAllPlanMetersRequest) (*GetAllPlanMetersResponse, error)
	CreatePlanMeter(context.Context, *CreatePlanMeterRequest) (*CreatePlanMeterResponse, error)
	UpdatePlanMeter(context.Context, *UpdatePlanMeterRequest) (*UpdatePlanMeterResponse, error)
	DeletePlanMeter(context.Context, *DeletePlanMeterRequest) (*DeletePlanMeterResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedProductServiceServer) GetProductBySlug(context.Context, *GetProductBySlugRequest) (*GetProductBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductBySlug not implemented")
}
func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductServiceServer) GetAllProducts(context.Context, *GetAllProductsRequest) (*GetAllProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllProducts not implemented")
}
func (UnimplementedProductServiceServer) GetPlanByID(context.Context, *GetPlanByIDRequest) (*GetPlanByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanByID not implemented")
}
func (UnimplementedProductServiceServer) GetPlanBySlug(context.Context, *GetPlanBySlugRequest) (*GetPlanBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanBySlug not implemented")
}
func (UnimplementedProductServiceServer) GetPlansByProduct(context.Context, *GetPlansByProductRequest) (*GetPlansByProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlansByProduct not implemented")
}
func (UnimplementedProductServiceServer) CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedProductServiceServer) UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (UnimplementedProductServiceServer) DeletePlan(context.Context, *DeletePlanRequest) (*DeletePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlan not implemented")
}
func (UnimplementedProductServiceServer) GetAllPlans(context.Context, *GetAllPlansRequest) (*GetAllPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPlans not implemented")
}
func (UnimplementedProductServiceServer) GetPlanPrice(context.Context, *GetPlanPriceRequest) (*GetPlanPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanPrice not implemented")
}
func (UnimplementedProductServiceServer) GetPlanPricesByPlan(context.Context, *GetPlanPricesByPlanRequest) (*GetPlanPricesByPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanPricesByPlan not implemented")
}
func (UnimplementedProductServiceServer) CreatePlanPrice(context.Context, *CreatePlanPriceRequest) (*CreatePlanPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlanPrice not implemented")
}
func (UnimplementedProductServiceServer) UpdatePlanPrice(context.Context, *UpdatePlanPriceRequest) (*UpdatePlanPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlanPrice not implemented")
}
func (UnimplementedProductServiceServer) DeletePlanPrice(context.Context, *DeletePlanPriceRequest) (*DeletePlanPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlanPrice not implemented")
}
func (UnimplementedProductServiceServer) GetPlanMeterByID(context.Context, *GetPlanMeterByIDRequest) (*GetPlanMeterByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanMeterByID not implemented")
}
func (UnimplementedProductServiceServer) GetAllPlanMeters(context.Context, *GetAllPlanMetersRequest) (*GetAllPlanMetersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPlanMeters not implemented")
}
func (UnimplementedProductServiceServer) CreatePlanMeter(context.Context, *CreatePlanMeterRequest) (*CreatePlanMeterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlanMeter not implemented")
}
func (UnimplementedProductServiceServer) UpdatePlanMeter(context.Context, *UpdatePlanMeterRequest) (*UpdatePlanMeterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlanMeter not implemented")
}
func (UnimplementedProductServiceServer) DeletePlanMeter(context.Context, *DeletePlanMeterRequest) (*DeletePlanMeterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlanMeter not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductBySlug(ctx, req.(*GetProductBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetAllProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAllProducts(ctx, req.(*GetAllProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlanByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlanByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlanByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlanByID(ctx, req.(*GetPlanByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlanBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlanBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlanBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlanBySlug(ctx, req.(*GetPlanBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlansByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlansByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlansByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlansByProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlansByProduct(ctx, req.(*GetPlansByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdatePlan(ctx, req.(*UpdatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeletePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeletePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeletePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeletePlan(ctx, req.(*DeletePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAllPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAllPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetAllPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAllPlans(ctx, req.(*GetAllPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlanPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlanPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlanPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlanPrice(ctx, req.(*GetPlanPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlanPricesByPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanPricesByPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlanPricesByPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlanPricesByPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlanPricesByPlan(ctx, req.(*GetPlanPricesByPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreatePlanPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreatePlanPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreatePlanPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreatePlanPrice(ctx, req.(*CreatePlanPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdatePlanPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdatePlanPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdatePlanPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdatePlanPrice(ctx, req.(*UpdatePlanPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeletePlanPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeletePlanPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeletePlanPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeletePlanPrice(ctx, req.(*DeletePlanPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPlanMeterByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanMeterByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPlanMeterByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetPlanMeterByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPlanMeterByID(ctx, req.(*GetPlanMeterByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAllPlanMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPlanMetersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAllPlanMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetAllPlanMeters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAllPlanMeters(ctx, req.(*GetAllPlanMetersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreatePlanMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreatePlanMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreatePlanMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreatePlanMeter(ctx, req.(*CreatePlanMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdatePlanMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdatePlanMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdatePlanMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdatePlanMeter(ctx, req.(*UpdatePlanMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeletePlanMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeletePlanMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeletePlanMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeletePlanMeter(ctx, req.(*DeletePlanMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
		{
			MethodName: "GetProductBySlug",
			Handler:    _ProductService_GetProductBySlug_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "GetAllProducts",
			Handler:    _ProductService_GetAllProducts_Handler,
		},
		{
			MethodName: "GetPlanByID",
			Handler:    _ProductService_GetPlanByID_Handler,
		},
		{
			MethodName: "GetPlanBySlug",
			Handler:    _ProductService_GetPlanBySlug_Handler,
		},
		{
			MethodName: "GetPlansByProduct",
			Handler:    _ProductService_GetPlansByProduct_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _ProductService_CreatePlan_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _ProductService_UpdatePlan_Handler,
		},
		{
			MethodName: "DeletePlan",
			Handler:    _ProductService_DeletePlan_Handler,
		},
		{
			MethodName: "GetAllPlans",
			Handler:    _ProductService_GetAllPlans_Handler,
		},
		{
			MethodName: "GetPlanPrice",
			Handler:    _ProductService_GetPlanPrice_Handler,
		},
		{
			MethodName: "GetPlanPricesByPlan",
			Handler:    _ProductService_GetPlanPricesByPlan_Handler,
		},
		{
			MethodName: "CreatePlanPrice",
			Handler:    _ProductService_CreatePlanPrice_Handler,
		},
		{
			MethodName: "UpdatePlanPrice",
			Handler:    _ProductService_UpdatePlanPrice_Handler,
		},
		{
			MethodName: "DeletePlanPrice",
			Handler:    _ProductService_DeletePlanPrice_Handler,
		},
		{
			MethodName: "GetPlanMeterByID",
			Handler:    _ProductService_GetPlanMeterByID_Handler,
		},
		{
			MethodName: "GetAllPlanMeters",
			Handler:    _ProductService_GetAllPlanMeters_Handler,
		},
		{
			MethodName: "CreatePlanMeter",
			Handler:    _ProductService_CreatePlanMeter_Handler,
		},
		{
			MethodName: "UpdatePlanMeter",
			Handler:    _ProductService_UpdatePlanMeter_Handler,
		},
		{
			MethodName: "DeletePlanMeter",
			Handler:    _ProductService_DeletePlanMeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
