// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: tenant.proto

package tenant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug                string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Domain              string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	IsNameAutoGenerated bool                   `protobuf:"varint,6,opt,name=is_name_auto_generated,json=isNameAutoGenerated,proto3" json:"is_name_auto_generated,omitempty"`
	CreatedBy           int64                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tenant) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Tenant) GetIsNameAutoGenerated() bool {
	if x != nil {
		return x.IsNameAutoGenerated
	}
	return false
}

func (x *Tenant) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Tenant) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tenant) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TenantUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUser) Reset() {
	*x = TenantUser{}
	mi := &file_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUser) ProtoMessage() {}

func (x *TenantUser) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUser.ProtoReflect.Descriptor instead.
func (*TenantUser) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TenantUser) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TenantUser) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *TenantUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantUser) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TenantUser) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TenantSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSetting) Reset() {
	*x = TenantSetting{}
	mi := &file_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSetting) ProtoMessage() {}

func (x *TenantSetting) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSetting.ProtoReflect.Descriptor instead.
func (*TenantSetting) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantSetting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantSetting) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TenantSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TenantSetting) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TenantSetting) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetTenantByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByIDRequest) Reset() {
	*x = GetTenantByIDRequest{}
	mi := &file_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByIDRequest) ProtoMessage() {}

func (x *GetTenantByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTenantByIDRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTenantByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Tenant                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByIDResponse) Reset() {
	*x = GetTenantByIDResponse{}
	mi := &file_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByIDResponse) ProtoMessage() {}

func (x *GetTenantByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTenantByIDResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenantByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTenantByIDResponse) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTenantByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByUUIDRequest) Reset() {
	*x = GetTenantByUUIDRequest{}
	mi := &file_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByUUIDRequest) ProtoMessage() {}

func (x *GetTenantByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetTenantByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetTenantByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Tenant                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByUUIDResponse) Reset() {
	*x = GetTenantByUUIDResponse{}
	mi := &file_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByUUIDResponse) ProtoMessage() {}

func (x *GetTenantByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetTenantByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *GetTenantByUUIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenantByUUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTenantByUUIDResponse) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTenantBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantBySlugRequest) Reset() {
	*x = GetTenantBySlugRequest{}
	mi := &file_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantBySlugRequest) ProtoMessage() {}

func (x *GetTenantBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetTenantBySlugRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *GetTenantBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetTenantBySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Tenant                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantBySlugResponse) Reset() {
	*x = GetTenantBySlugResponse{}
	mi := &file_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantBySlugResponse) ProtoMessage() {}

func (x *GetTenantBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetTenantBySlugResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *GetTenantBySlugResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenantBySlugResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTenantBySlugResponse) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTenantRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateTenantRequest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Tenant                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTenantResponse) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTenantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTenantRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Tenant                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTenantResponse) GetData() *Tenant {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTenantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTenantsRequest) Reset() {
	*x = GetAllTenantsRequest{}
	mi := &file_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTenantsRequest) ProtoMessage() {}

func (x *GetAllTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllTenantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllTenantsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllTenantsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllTenantsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetAllTenantsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetAllTenantsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTenantsData) Reset() {
	*x = GetAllTenantsData{}
	mi := &file_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTenantsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTenantsData) ProtoMessage() {}

func (x *GetAllTenantsData) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTenantsData.ProtoReflect.Descriptor instead.
func (*GetAllTenantsData) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllTenantsData) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *GetAllTenantsData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllTenantsData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllTenantsData) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetAllTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetAllTenantsData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTenantsResponse) Reset() {
	*x = GetAllTenantsResponse{}
	mi := &file_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTenantsResponse) ProtoMessage() {}

func (x *GetAllTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllTenantsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllTenantsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllTenantsResponse) GetData() *GetAllTenantsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddUserToTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToTenantRequest) Reset() {
	*x = AddUserToTenantRequest{}
	mi := &file_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToTenantRequest) ProtoMessage() {}

func (x *AddUserToTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToTenantRequest.ProtoReflect.Descriptor instead.
func (*AddUserToTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *AddUserToTenantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddUserToTenantRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *AddUserToTenantRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddUserToTenantRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *AddUserToTenantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddUserToTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TenantUser            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToTenantResponse) Reset() {
	*x = AddUserToTenantResponse{}
	mi := &file_tenant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToTenantResponse) ProtoMessage() {}

func (x *AddUserToTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToTenantResponse.ProtoReflect.Descriptor instead.
func (*AddUserToTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{19}
}

func (x *AddUserToTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddUserToTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddUserToTenantResponse) GetData() *TenantUser {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemoveUserFromTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTenantRequest) Reset() {
	*x = RemoveUserFromTenantRequest{}
	mi := &file_tenant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTenantRequest) ProtoMessage() {}

func (x *RemoveUserFromTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTenantRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveUserFromTenantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserFromTenantRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type RemoveUserFromTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTenantResponse) Reset() {
	*x = RemoveUserFromTenantResponse{}
	mi := &file_tenant_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTenantResponse) ProtoMessage() {}

func (x *RemoveUserFromTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTenantResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveUserFromTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveUserFromTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTenantUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUsersRequest) Reset() {
	*x = GetTenantUsersRequest{}
	mi := &file_tenant_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUsersRequest) ProtoMessage() {}

func (x *GetTenantUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUsersRequest.ProtoReflect.Descriptor instead.
func (*GetTenantUsersRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{22}
}

func (x *GetTenantUsersRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetTenantUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TenantUser          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUsersResponse) Reset() {
	*x = GetTenantUsersResponse{}
	mi := &file_tenant_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUsersResponse) ProtoMessage() {}

func (x *GetTenantUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTenantUsersResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{23}
}

func (x *GetTenantUsersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenantUsersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTenantUsersResponse) GetData() []*TenantUser {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTenantsRequest) Reset() {
	*x = GetUserTenantsRequest{}
	mi := &file_tenant_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTenantsRequest) ProtoMessage() {}

func (x *GetUserTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserTenantsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TenantUser          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTenantsResponse) Reset() {
	*x = GetUserTenantsResponse{}
	mi := &file_tenant_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTenantsResponse) ProtoMessage() {}

func (x *GetUserTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserTenantsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserTenantsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserTenantsResponse) GetData() []*TenantUser {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleRequest) Reset() {
	*x = UpdateUserRoleRequest{}
	mi := &file_tenant_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleRequest) ProtoMessage() {}

func (x *UpdateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateUserRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRoleRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleResponse) Reset() {
	*x = UpdateUserRoleResponse{}
	mi := &file_tenant_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleResponse) ProtoMessage() {}

func (x *UpdateUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetDefaultTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultTenantRequest) Reset() {
	*x = SetDefaultTenantRequest{}
	mi := &file_tenant_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultTenantRequest) ProtoMessage() {}

func (x *SetDefaultTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultTenantRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{28}
}

func (x *SetDefaultTenantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetDefaultTenantRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type SetDefaultTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultTenantResponse) Reset() {
	*x = SetDefaultTenantResponse{}
	mi := &file_tenant_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultTenantResponse) ProtoMessage() {}

func (x *SetDefaultTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultTenantResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{29}
}

func (x *SetDefaultTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDefaultTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_tenant_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{30}
}

func (x *GetSettingRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TenantSetting         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingResponse) Reset() {
	*x = GetSettingResponse{}
	mi := &file_tenant_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingResponse) ProtoMessage() {}

func (x *GetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSettingResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{31}
}

func (x *GetSettingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSettingResponse) GetData() *TenantSetting {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSettingsRequest) Reset() {
	*x = GetAllSettingsRequest{}
	mi := &file_tenant_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSettingsRequest) ProtoMessage() {}

func (x *GetAllSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSettingsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{32}
}

func (x *GetAllSettingsRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetAllSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TenantSetting       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSettingsResponse) Reset() {
	*x = GetAllSettingsResponse{}
	mi := &file_tenant_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSettingsResponse) ProtoMessage() {}

func (x *GetAllSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSettingsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{33}
}

func (x *GetAllSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllSettingsResponse) GetData() []*TenantSetting {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingRequest) Reset() {
	*x = SetSettingRequest{}
	mi := &file_tenant_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingRequest) ProtoMessage() {}

func (x *SetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingRequest.ProtoReflect.Descriptor instead.
func (*SetSettingRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{34}
}

func (x *SetSettingRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *SetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TenantSetting         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingResponse) Reset() {
	*x = SetSettingResponse{}
	mi := &file_tenant_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingResponse) ProtoMessage() {}

func (x *SetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingResponse.ProtoReflect.Descriptor instead.
func (*SetSettingResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{35}
}

func (x *SetSettingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetSettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetSettingResponse) GetData() *TenantSetting {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSettingRequest) Reset() {
	*x = DeleteSettingRequest{}
	mi := &file_tenant_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSettingRequest) ProtoMessage() {}

func (x *DeleteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSettingRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteSettingRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeleteSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSettingResponse) Reset() {
	*x = DeleteSettingResponse{}
	mi := &file_tenant_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSettingResponse) ProtoMessage() {}

func (x *DeleteSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSettingResponse.ProtoReflect.Descriptor instead.
func (*DeleteSettingResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteSettingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tenant_proto protoreflect.FileDescriptor

const file_tenant_proto_rawDesc = "" +
	"\n" +
	"\ftenant.proto\x12\x06tenant\"\xfe\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x123\n" +
	"\x16is_name_auto_generated\x18\x06 \x01(\bR\x13isNameAutoGenerated\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xd9\x01\n" +
	"\n" +
	"TenantUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xa2\x01\n" +
	"\rTenantSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"&\n" +
	"\x14GetTenantByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"o\n" +
	"\x15GetTenantByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.tenant.TenantR\x04data\",\n" +
	"\x16GetTenantByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"q\n" +
	"\x17GetTenantByUUIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.tenant.TenantR\x04data\",\n" +
	"\x16GetTenantBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"q\n" +
	"\x17GetTenantBySlugResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.tenant.TenantR\x04data\"t\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x03R\tcreatedBy\"n\n" +
	"\x14CreateTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.tenant.TenantR\x04data\"Q\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"n\n" +
	"\x14UpdateTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.tenant.TenantR\x04data\"%\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"J\n" +
	"\x14DeleteTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\x14GetAllTenantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\"\x82\x01\n" +
	"\x11GetAllTenantsData\x12(\n" +
	"\atenants\x18\x01 \x03(\v2\x0e.tenant.TenantR\atenants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"z\n" +
	"\x15GetAllTenantsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.tenant.GetAllTenantsDataR\x04data\"\x97\x01\n" +
	"\x16AddUserToTenantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"u\n" +
	"\x17AddUserToTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.tenant.TenantUserR\x04data\"S\n" +
	"\x1bRemoveUserFromTenantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"R\n" +
	"\x1cRemoveUserFromTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x15GetTenantUsersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\"t\n" +
	"\x16GetTenantUsersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.tenant.TenantUserR\x04data\"0\n" +
	"\x15GetUserTenantsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"t\n" +
	"\x16GetUserTenantsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.tenant.TenantUserR\x04data\"a\n" +
	"\x15UpdateUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"L\n" +
	"\x16UpdateUserRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x17SetDefaultTenantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"N\n" +
	"\x18SetDefaultTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x11GetSettingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"s\n" +
	"\x12GetSettingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.tenant.TenantSettingR\x04data\"4\n" +
	"\x15GetAllSettingsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\"w\n" +
	"\x16GetAllSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.tenant.TenantSettingR\x04data\"X\n" +
	"\x11SetSettingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"s\n" +
	"\x12SetSettingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.tenant.TenantSettingR\x04data\"E\n" +
	"\x14DeleteSettingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"K\n" +
	"\x15DeleteSettingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x80\v\n" +
	"\rTenantService\x12N\n" +
	"\rGetTenantByID\x12\x1c.tenant.GetTenantByIDRequest\x1a\x1d.tenant.GetTenantByIDResponse\"\x00\x12T\n" +
	"\x0fGetTenantByUUID\x12\x1e.tenant.GetTenantByUUIDRequest\x1a\x1f.tenant.GetTenantByUUIDResponse\"\x00\x12T\n" +
	"\x0fGetTenantBySlug\x12\x1e.tenant.GetTenantBySlugRequest\x1a\x1f.tenant.GetTenantBySlugResponse\"\x00\x12K\n" +
	"\fCreateTenant\x12\x1b.tenant.CreateTenantRequest\x1a\x1c.tenant.CreateTenantResponse\"\x00\x12K\n" +
	"\fUpdateTenant\x12\x1b.tenant.UpdateTenantRequest\x1a\x1c.tenant.UpdateTenantResponse\"\x00\x12K\n" +
	"\fDeleteTenant\x12\x1b.tenant.DeleteTenantRequest\x1a\x1c.tenant.DeleteTenantResponse\"\x00\x12N\n" +
	"\rGetAllTenants\x12\x1c.tenant.GetAllTenantsRequest\x1a\x1d.tenant.GetAllTenantsResponse\"\x00\x12T\n" +
	"\x0fAddUserToTenant\x12\x1e.tenant.AddUserToTenantRequest\x1a\x1f.tenant.AddUserToTenantResponse\"\x00\x12c\n" +
	"\x14RemoveUserFromTenant\x12#.tenant.RemoveUserFromTenantRequest\x1a$.tenant.RemoveUserFromTenantResponse\"\x00\x12Q\n" +
	"\x0eGetTenantUsers\x12\x1d.tenant.GetTenantUsersRequest\x1a\x1e.tenant.GetTenantUsersResponse\"\x00\x12Q\n" +
	"\x0eGetUserTenants\x12\x1d.tenant.GetUserTenantsRequest\x1a\x1e.tenant.GetUserTenantsResponse\"\x00\x12Q\n" +
	"\x0eUpdateUserRole\x12\x1d.tenant.UpdateUserRoleRequest\x1a\x1e.tenant.UpdateUserRoleResponse\"\x00\x12W\n" +
	"\x10SetDefaultTenant\x12\x1f.tenant.SetDefaultTenantRequest\x1a .tenant.SetDefaultTenantResponse\"\x00\x12E\n" +
	"\n" +
	"GetSetting\x12\x19.tenant.GetSettingRequest\x1a\x1a.tenant.GetSettingResponse\"\x00\x12Q\n" +
	"\x0eGetAllSettings\x12\x1d.tenant.GetAllSettingsRequest\x1a\x1e.tenant.GetAllSettingsResponse\"\x00\x12E\n" +
	"\n" +
	"SetSetting\x12\x19.tenant.SetSettingRequest\x1a\x1a.tenant.SetSettingResponse\"\x00\x12N\n" +
	"\rDeleteSetting\x12\x1c.tenant.DeleteSettingRequest\x1a\x1d.tenant.DeleteSettingResponse\"\x00B\x1cZ\x1ashared/proto/tenant;tenantb\x06proto3"

var (
	file_tenant_proto_rawDescOnce sync.Once
	file_tenant_proto_rawDescData []byte
)

func file_tenant_proto_rawDescGZIP() []byte {
	file_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)))
	})
	return file_tenant_proto_rawDescData
}

var file_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                       // 0: tenant.Tenant
	(*TenantUser)(nil),                   // 1: tenant.TenantUser
	(*TenantSetting)(nil),                // 2: tenant.TenantSetting
	(*GetTenantByIDRequest)(nil),         // 3: tenant.GetTenantByIDRequest
	(*GetTenantByIDResponse)(nil),        // 4: tenant.GetTenantByIDResponse
	(*GetTenantByUUIDRequest)(nil),       // 5: tenant.GetTenantByUUIDRequest
	(*GetTenantByUUIDResponse)(nil),      // 6: tenant.GetTenantByUUIDResponse
	(*GetTenantBySlugRequest)(nil),       // 7: tenant.GetTenantBySlugRequest
	(*GetTenantBySlugResponse)(nil),      // 8: tenant.GetTenantBySlugResponse
	(*CreateTenantRequest)(nil),          // 9: tenant.CreateTenantRequest
	(*CreateTenantResponse)(nil),         // 10: tenant.CreateTenantResponse
	(*UpdateTenantRequest)(nil),          // 11: tenant.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),         // 12: tenant.UpdateTenantResponse
	(*DeleteTenantRequest)(nil),          // 13: tenant.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),         // 14: tenant.DeleteTenantResponse
	(*GetAllTenantsRequest)(nil),         // 15: tenant.GetAllTenantsRequest
	(*GetAllTenantsData)(nil),            // 16: tenant.GetAllTenantsData
	(*GetAllTenantsResponse)(nil),        // 17: tenant.GetAllTenantsResponse
	(*AddUserToTenantRequest)(nil),       // 18: tenant.AddUserToTenantRequest
	(*AddUserToTenantResponse)(nil),      // 19: tenant.AddUserToTenantResponse
	(*RemoveUserFromTenantRequest)(nil),  // 20: tenant.RemoveUserFromTenantRequest
	(*RemoveUserFromTenantResponse)(nil), // 21: tenant.RemoveUserFromTenantResponse
	(*GetTenantUsersRequest)(nil),        // 22: tenant.GetTenantUsersRequest
	(*GetTenantUsersResponse)(nil),       // 23: tenant.GetTenantUsersResponse
	(*GetUserTenantsRequest)(nil),        // 24: tenant.GetUserTenantsRequest
	(*GetUserTenantsResponse)(nil),       // 25: tenant.GetUserTenantsResponse
	(*UpdateUserRoleRequest)(nil),        // 26: tenant.UpdateUserRoleRequest
	(*UpdateUserRoleResponse)(nil),       // 27: tenant.UpdateUserRoleResponse
	(*SetDefaultTenantRequest)(nil),      // 28: tenant.SetDefaultTenantRequest
	(*SetDefaultTenantResponse)(nil),     // 29: tenant.SetDefaultTenantResponse
	(*GetSettingRequest)(nil),            // 30: tenant.GetSettingRequest
	(*GetSettingResponse)(nil),           // 31: tenant.GetSettingResponse
	(*GetAllSettingsRequest)(nil),        // 32: tenant.GetAllSettingsRequest
	(*GetAllSettingsResponse)(nil),       // 33: tenant.GetAllSettingsResponse
	(*SetSettingRequest)(nil),            // 34: tenant.SetSettingRequest
	(*SetSettingResponse)(nil),           // 35: tenant.SetSettingResponse
	(*DeleteSettingRequest)(nil),         // 36: tenant.DeleteSettingRequest
	(*DeleteSettingResponse)(nil),        // 37: tenant.DeleteSettingResponse
}
var file_tenant_proto_depIdxs = []int32{
	0,  // 0: tenant.GetTenantByIDResponse.data:type_name -> tenant.Tenant
	0,  // 1: tenant.GetTenantByUUIDResponse.data:type_name -> tenant.Tenant
	0,  // 2: tenant.GetTenantBySlugResponse.data:type_name -> tenant.Tenant
	0,  // 3: tenant.CreateTenantResponse.data:type_name -> tenant.Tenant
	0,  // 4: tenant.UpdateTenantResponse.data:type_name -> tenant.Tenant
	0,  // 5: tenant.GetAllTenantsData.tenants:type_name -> tenant.Tenant
	16, // 6: tenant.GetAllTenantsResponse.data:type_name -> tenant.GetAllTenantsData
	1,  // 7: tenant.AddUserToTenantResponse.data:type_name -> tenant.TenantUser
	1,  // 8: tenant.GetTenantUsersResponse.data:type_name -> tenant.TenantUser
	1,  // 9: tenant.GetUserTenantsResponse.data:type_name -> tenant.TenantUser
	2,  // 10: tenant.GetSettingResponse.data:type_name -> tenant.TenantSetting
	2,  // 11: tenant.GetAllSettingsResponse.data:type_name -> tenant.TenantSetting
	2,  // 12: tenant.SetSettingResponse.data:type_name -> tenant.TenantSetting
	3,  // 13: tenant.TenantService.GetTenantByID:input_type -> tenant.GetTenantByIDRequest
	5,  // 14: tenant.TenantService.GetTenantByUUID:input_type -> tenant.GetTenantByUUIDRequest
	7,  // 15: tenant.TenantService.GetTenantBySlug:input_type -> tenant.GetTenantBySlugRequest
	9,  // 16: tenant.TenantService.CreateTenant:input_type -> tenant.CreateTenantRequest
	11, // 17: tenant.TenantService.UpdateTenant:input_type -> tenant.UpdateTenantRequest
	13, // 18: tenant.TenantService.DeleteTenant:input_type -> tenant.DeleteTenantRequest
	15, // 19: tenant.TenantService.GetAllTenants:input_type -> tenant.GetAllTenantsRequest
	18, // 20: tenant.TenantService.AddUserToTenant:input_type -> tenant.AddUserToTenantRequest
	20, // 21: tenant.TenantService.RemoveUserFromTenant:input_type -> tenant.RemoveUserFromTenantRequest
	22, // 22: tenant.TenantService.GetTenantUsers:input_type -> tenant.GetTenantUsersRequest
	24, // 23: tenant.TenantService.GetUserTenants:input_type -> tenant.GetUserTenantsRequest
	26, // 24: tenant.TenantService.UpdateUserRole:input_type -> tenant.UpdateUserRoleRequest
	28, // 25: tenant.TenantService.SetDefaultTenant:input_type -> tenant.SetDefaultTenantRequest
	30, // 26: tenant.TenantService.GetSetting:input_type -> tenant.GetSettingRequest
	32, // 27: tenant.TenantService.GetAllSettings:input_type -> tenant.GetAllSettingsRequest
	34, // 28: tenant.TenantService.SetSetting:input_type -> tenant.SetSettingRequest
	36, // 29: tenant.TenantService.DeleteSetting:input_type -> tenant.DeleteSettingRequest
	4,  // 30: tenant.TenantService.GetTenantByID:output_type -> tenant.GetTenantByIDResponse
	6,  // 31: tenant.TenantService.GetTenantByUUID:output_type -> tenant.GetTenantByUUIDResponse
	8,  // 32: tenant.TenantService.GetTenantBySlug:output_type -> tenant.GetTenantBySlugResponse
	10, // 33: tenant.TenantService.CreateTenant:output_type -> tenant.CreateTenantResponse
	12, // 34: tenant.TenantService.UpdateTenant:output_type -> tenant.UpdateTenantResponse
	14, // 35: tenant.TenantService.DeleteTenant:output_type -> tenant.DeleteTenantResponse
	17, // 36: tenant.TenantService.GetAllTenants:output_type -> tenant.GetAllTenantsResponse
	19, // 37: tenant.TenantService.AddUserToTenant:output_type -> tenant.AddUserToTenantResponse
	21, // 38: tenant.TenantService.RemoveUserFromTenant:output_type -> tenant.RemoveUserFromTenantResponse
	23, // 39: tenant.TenantService.GetTenantUsers:output_type -> tenant.GetTenantUsersResponse
	25, // 40: tenant.TenantService.GetUserTenants:output_type -> tenant.GetUserTenantsResponse
	27, // 41: tenant.TenantService.UpdateUserRole:output_type -> tenant.UpdateUserRoleResponse
	29, // 42: tenant.TenantService.SetDefaultTenant:output_type -> tenant.SetDefaultTenantResponse
	31, // 43: tenant.TenantService.GetSetting:output_type -> tenant.GetSettingResponse
	33, // 44: tenant.TenantService.GetAllSettings:output_type -> tenant.GetAllSettingsResponse
	35, // 45: tenant.TenantService.SetSetting:output_type -> tenant.SetSettingResponse
	37, // 46: tenant.TenantService.DeleteSetting:output_type -> tenant.DeleteSettingResponse
	30, // [30:47] is the sub-list for method output_type
	13, // [13:30] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tenant_proto_init() }
func file_tenant_proto_init() {
	if File_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_proto_depIdxs,
		MessageInfos:      file_tenant_proto_msgTypes,
	}.Build()
	File_tenant_proto = out.File
	file_tenant_proto_goTypes = nil
	file_tenant_proto_depIdxs = nil
}
