package domain

import (
	"context"
	"encoding/json"
	"time"
)

// Tenant represents a tenant/organization entity
type Tenant struct {
	ID                  int64
	UUID                string
	Name                string
	Slug                string
	Domain              *string
	IsNameAutoGenerated bool
	CreatedBy           *int64
	CreatedAt           *time.Time
	UpdatedAt           *time.Time
	DeletedAt           *time.Time
}

// TenantUser represents the relationship between a user and tenant
type TenantUser struct {
	ID        int64
	UserID    int64
	TenantID  int64
	Role      string // owner, admin, member, guest
	IsDefault bool
	Email     *string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// TenantSetting represents tenant-specific configuration
type TenantSetting struct {
	ID        int64
	TenantID  int64
	Key       string
	Value     json.RawMessage
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// TenantRepository defines the interface for tenant data access
type TenantRepository interface {
	// Tenant operations
	GetByID(ctx context.Context, id int64) (*Tenant, error)
	GetByUUID(ctx context.Context, uuid string) (*Tenant, error)
	GetBySlug(ctx context.Context, slug string) (*Tenant, error)
	GetByDomain(ctx context.Context, domain string) (*Tenant, error)
	Create(ctx context.Context, tenant *Tenant) (*Tenant, error)
	Update(ctx context.Context, tenant *Tenant) (*Tenant, error)
	Delete(ctx context.Context, id int64) error
	GetAll(ctx context.Context, page, perPage int) ([]*Tenant, int64, error)

	// TenantUser operations
	AddUserToTenant(ctx context.Context, tenantUser *TenantUser) (*TenantUser, error)
	RemoveUserFromTenant(ctx context.Context, userID, tenantID int64) error
	GetTenantUsers(ctx context.Context, tenantID int64) ([]*TenantUser, error)
	GetUserTenants(ctx context.Context, userID int64) ([]*TenantUser, error)
	GetUserTenantRole(ctx context.Context, userID, tenantID int64) (*TenantUser, error)
	UpdateUserRole(ctx context.Context, userID, tenantID int64, role string) error
	SetDefaultTenant(ctx context.Context, userID, tenantID int64) error

	// TenantSetting operations
	GetSetting(ctx context.Context, tenantID int64, key string) (*TenantSetting, error)
	GetAllSettings(ctx context.Context, tenantID int64) ([]*TenantSetting, error)
	SetSetting(ctx context.Context, setting *TenantSetting) (*TenantSetting, error)
	DeleteSetting(ctx context.Context, tenantID int64, key string) error
}

// TenantService defines business logic for tenants
type TenantService interface {
	// Tenant operations
	GetTenantByID(ctx context.Context, id int64) (*Tenant, error)
	GetTenantByUUID(ctx context.Context, uuid string) (*Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error)
	GetTenantByDomain(ctx context.Context, domain string) (*Tenant, error)
	CreateTenant(ctx context.Context, tenant *Tenant) (*Tenant, error)
	UpdateTenant(ctx context.Context, tenant *Tenant) (*Tenant, error)
	DeleteTenant(ctx context.Context, id int64) error
	GetAllTenants(ctx context.Context, page, perPage int) ([]*Tenant, int64, error)

	// TenantUser operations
	AddUserToTenant(ctx context.Context, tenantUser *TenantUser) (*TenantUser, error)
	RemoveUserFromTenant(ctx context.Context, userID, tenantID int64) error
	GetTenantUsers(ctx context.Context, tenantID int64) ([]*TenantUser, error)
	GetUserTenants(ctx context.Context, userID int64) ([]*TenantUser, error)
	GetUserTenantRole(ctx context.Context, userID, tenantID int64) (*TenantUser, error)
	UpdateUserRole(ctx context.Context, userID, tenantID int64, role string) error
	SetDefaultTenant(ctx context.Context, userID, tenantID int64) error

	// TenantSetting operations
	GetSetting(ctx context.Context, tenantID int64, key string) (*TenantSetting, error)
	GetAllSettings(ctx context.Context, tenantID int64) ([]*TenantSetting, error)
	SetSetting(ctx context.Context, setting *TenantSetting) (*TenantSetting, error)
	DeleteSetting(ctx context.Context, tenantID int64, key string) error
}
