// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddUserToTenantInput struct {
	UserID    string `json:"userId"`
	TenantID  string `json:"tenantId"`
	Role      string `json:"role"`
	IsDefault *bool  `json:"isDefault,omitempty"`
}

type BulkOperationResponse struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	AffectedCount int32  `json:"affectedCount"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateTenantInput struct {
	Name   string  `json:"name"`
	Slug   *string `json:"slug,omitempty"`
	Domain *string `json:"domain,omitempty"`
}

type CreateUserInput struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	PublicName  *string `json:"publicName,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Position    *string `json:"position,omitempty"`
	IsAdmin     *bool   `json:"isAdmin,omitempty"`
}

type DeleteSettingResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DeleteTenantResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DeleteUserResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ForgotPasswordResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type LoginData struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Success bool       `json:"success"`
	Message string     `json:"message"`
	Data    *LoginData `json:"data,omitempty"`
}

type LogoutResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshTokenData struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	Success bool              `json:"success"`
	Message string            `json:"message"`
	Data    *RefreshTokenData `json:"data,omitempty"`
}

type ResetPasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type ResetPasswordResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type SetDefaultTenantInput struct {
	UserID   string `json:"userId"`
	TenantID string `json:"tenantId"`
}

type SetDefaultTenantResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type SetSettingInput struct {
	TenantID string `json:"tenantId"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type Tenant struct {
	ID                  string  `json:"id"`
	UUID                string  `json:"uuid"`
	Name                string  `json:"name"`
	Slug                string  `json:"slug"`
	Domain              *string `json:"domain,omitempty"`
	IsNameAutoGenerated bool    `json:"isNameAutoGenerated"`
	CreatedBy           string  `json:"createdBy"`
	CreatedAt           int32   `json:"createdAt"`
	UpdatedAt           int32   `json:"updatedAt"`
}

type TenantList struct {
	Tenants []*Tenant `json:"tenants"`
	Total   int32     `json:"total"`
	Page    int32     `json:"page"`
	PerPage int32     `json:"perPage"`
}

type TenantListResponse struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *TenantList `json:"data,omitempty"`
}

type TenantResponse struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Data    *Tenant `json:"data,omitempty"`
}

type TenantSetting struct {
	ID        string `json:"id"`
	TenantID  string `json:"tenantId"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt int32  `json:"createdAt"`
	UpdatedAt int32  `json:"updatedAt"`
}

type TenantSettingResponse struct {
	Success bool           `json:"success"`
	Message string         `json:"message"`
	Data    *TenantSetting `json:"data,omitempty"`
}

type TenantSettingsResponse struct {
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    []*TenantSetting `json:"data,omitempty"`
}

type TenantUser struct {
	ID        string `json:"id"`
	UserID    string `json:"userId"`
	TenantID  string `json:"tenantId"`
	Role      string `json:"role"`
	IsDefault bool   `json:"isDefault"`
	Email     string `json:"email"`
	CreatedAt int32  `json:"createdAt"`
	UpdatedAt int32  `json:"updatedAt"`
}

type TenantUserResponse struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *TenantUser `json:"data,omitempty"`
}

type TenantUsersResponse struct {
	Success bool          `json:"success"`
	Message string        `json:"message"`
	Data    []*TenantUser `json:"data,omitempty"`
}

type UpdateTenantInput struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Domain *string `json:"domain,omitempty"`
}

type UpdateUserInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Email       *string `json:"email,omitempty"`
	PublicName  *string `json:"publicName,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Position    *string `json:"position,omitempty"`
	IsAdmin     *bool   `json:"isAdmin,omitempty"`
	IsBlocked   *bool   `json:"isBlocked,omitempty"`
}

type UpdateUserRoleInput struct {
	UserID   string `json:"userId"`
	TenantID string `json:"tenantId"`
	Role     string `json:"role"`
}

type UpdateUserRoleResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type User struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Email           string  `json:"email"`
	PublicName      *string `json:"publicName,omitempty"`
	IsAdmin         bool    `json:"isAdmin"`
	IsBlocked       bool    `json:"isBlocked"`
	PhoneNumber     *string `json:"phoneNumber,omitempty"`
	Position        *string `json:"position,omitempty"`
	EmailVerified   bool    `json:"emailVerified"`
	EmailVerifiedAt *int32  `json:"emailVerifiedAt,omitempty"`
	LastLoginAt     *int32  `json:"lastLoginAt,omitempty"`
	CreatedAt       *int32  `json:"createdAt,omitempty"`
	UpdatedAt       *int32  `json:"updatedAt,omitempty"`
}

type UserList struct {
	Users   []*User `json:"users"`
	Total   int32   `json:"total"`
	Page    int32   `json:"page"`
	PerPage int32   `json:"perPage"`
}

type UserListResponse struct {
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *UserList `json:"data,omitempty"`
}

type UserResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type VerifyEmailResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
