// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelType            string                 `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ModelId              int64                  `protobuf:"varint,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Uuid                 string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CollectionName       string                 `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Name                 string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	FileName             string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType             string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Disk                 string                 `protobuf:"bytes,9,opt,name=disk,proto3" json:"disk,omitempty"`
	ConversionsDisk      string                 `protobuf:"bytes,10,opt,name=conversions_disk,json=conversionsDisk,proto3" json:"conversions_disk,omitempty"`
	Size                 int64                  `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	Manipulations        string                 `protobuf:"bytes,12,opt,name=manipulations,proto3" json:"manipulations,omitempty"`                                           // JSON string
	CustomProperties     string                 `protobuf:"bytes,13,opt,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty"`             // JSON string
	GeneratedConversions string                 `protobuf:"bytes,14,opt,name=generated_conversions,json=generatedConversions,proto3" json:"generated_conversions,omitempty"` // JSON string
	ResponsiveImages     string                 `protobuf:"bytes,15,opt,name=responsive_images,json=responsiveImages,proto3" json:"responsive_images,omitempty"`             // JSON string
	OrderColumn          int32                  `protobuf:"varint,16,opt,name=order_column,json=orderColumn,proto3" json:"order_column,omitempty"`
	CreatedAt            int64                  `protobuf:"varint,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64                  `protobuf:"varint,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PresignedUrl         string                 `protobuf:"bytes,19,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"` // Generated pre-signed URL for accessing file
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *Media) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Media) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Media) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Media) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *Media) GetConversionsDisk() string {
	if x != nil {
		return x.ConversionsDisk
	}
	return ""
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Media) GetManipulations() string {
	if x != nil {
		return x.Manipulations
	}
	return ""
}

func (x *Media) GetCustomProperties() string {
	if x != nil {
		return x.CustomProperties
	}
	return ""
}

func (x *Media) GetGeneratedConversions() string {
	if x != nil {
		return x.GeneratedConversions
	}
	return ""
}

func (x *Media) GetResponsiveImages() string {
	if x != nil {
		return x.ResponsiveImages
	}
	return ""
}

func (x *Media) GetOrderColumn() int32 {
	if x != nil {
		return x.OrderColumn
	}
	return 0
}

func (x *Media) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Media) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Media) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type UploadFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType       string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size           int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModelType      string                 `protobuf:"bytes,5,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ModelId        int64                  `protobuf:"varint,6,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	CollectionName string                 `protobuf:"bytes,7,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"` // Optional custom name
	Disk           string                 `protobuf:"bytes,9,opt,name=disk,proto3" json:"disk,omitempty"` // Storage disk identifier
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *UploadFileRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *UploadFileRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileRequest) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Media                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetData() *Media {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFileByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByIDRequest) Reset() {
	*x = GetFileByIDRequest{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByIDRequest) ProtoMessage() {}

func (x *GetFileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetFileByIDRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFileByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Media                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByIDResponse) Reset() {
	*x = GetFileByIDResponse{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByIDResponse) ProtoMessage() {}

func (x *GetFileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetFileByIDResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFileByIDResponse) GetData() *Media {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFileByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByUUIDRequest) Reset() {
	*x = GetFileByUUIDRequest{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByUUIDRequest) ProtoMessage() {}

func (x *GetFileByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetFileByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetFileByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Media                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByUUIDResponse) Reset() {
	*x = GetFileByUUIDResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByUUIDResponse) ProtoMessage() {}

func (x *GetFileByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetFileByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileByUUIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileByUUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFileByUUIDResponse) GetData() *Media {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFilesByModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelType      string                 `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ModelId        int64                  `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	CollectionName string                 `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Optional filter by collection
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PerPage        int32                  `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFilesByModelRequest) Reset() {
	*x = GetFilesByModelRequest{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByModelRequest) ProtoMessage() {}

func (x *GetFilesByModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByModelRequest.ProtoReflect.Descriptor instead.
func (*GetFilesByModelRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetFilesByModelRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *GetFilesByModelRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *GetFilesByModelRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetFilesByModelRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFilesByModelRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetFilesByModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetFilesByModelData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByModelResponse) Reset() {
	*x = GetFilesByModelResponse{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByModelResponse) ProtoMessage() {}

func (x *GetFilesByModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByModelResponse.ProtoReflect.Descriptor instead.
func (*GetFilesByModelResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetFilesByModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFilesByModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFilesByModelResponse) GetData() *GetFilesByModelData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFilesByModelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByModelData) Reset() {
	*x = GetFilesByModelData{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByModelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByModelData) ProtoMessage() {}

func (x *GetFilesByModelData) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByModelData.ProtoReflect.Descriptor instead.
func (*GetFilesByModelData) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetFilesByModelData) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetFilesByModelData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFilesByModelData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFilesByModelData) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFileURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpirySeconds int32                  `protobuf:"varint,2,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"` // Optional, default 900 (15 minutes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLRequest) Reset() {
	*x = GetFileURLRequest{}
	mi := &file_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLRequest) ProtoMessage() {}

func (x *GetFileURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLRequest.ProtoReflect.Descriptor instead.
func (*GetFileURLRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileURLRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFileURLRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type GetFileURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetFileURLData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLResponse) Reset() {
	*x = GetFileURLResponse{}
	mi := &file_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLResponse) ProtoMessage() {}

func (x *GetFileURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLResponse.ProtoReflect.Descriptor instead.
func (*GetFileURLResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFileURLResponse) GetData() *GetFileURLData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFileURLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLData) Reset() {
	*x = GetFileURLData{}
	mi := &file_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLData) ProtoMessage() {}

func (x *GetFileURLData) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLData.ProtoReflect.Descriptor instead.
func (*GetFileURLData) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileURLData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetFileURLData) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetAllMediaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage        int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	ModelType      string                 `protobuf:"bytes,3,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`                // Optional filter
	CollectionName string                 `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Optional filter
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllMediaRequest) Reset() {
	*x = GetAllMediaRequest{}
	mi := &file_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMediaRequest) ProtoMessage() {}

func (x *GetAllMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMediaRequest.ProtoReflect.Descriptor instead.
func (*GetAllMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllMediaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllMediaRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllMediaRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *GetAllMediaRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type GetAllMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetAllMediaData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMediaResponse) Reset() {
	*x = GetAllMediaResponse{}
	mi := &file_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMediaResponse) ProtoMessage() {}

func (x *GetAllMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMediaResponse.ProtoReflect.Descriptor instead.
func (*GetAllMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllMediaResponse) GetData() *GetAllMediaData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllMediaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMediaData) Reset() {
	*x = GetAllMediaData{}
	mi := &file_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMediaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMediaData) ProtoMessage() {}

func (x *GetAllMediaData) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMediaData.ProtoReflect.Descriptor instead.
func (*GetAllMediaData) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllMediaData) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetAllMediaData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllMediaData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllMediaData) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\"\xea\x04\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\x03R\amodelId\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12\x12\n" +
	"\x04disk\x18\t \x01(\tR\x04disk\x12)\n" +
	"\x10conversions_disk\x18\n" +
	" \x01(\tR\x0fconversionsDisk\x12\x12\n" +
	"\x04size\x18\v \x01(\x03R\x04size\x12$\n" +
	"\rmanipulations\x18\f \x01(\tR\rmanipulations\x12+\n" +
	"\x11custom_properties\x18\r \x01(\tR\x10customProperties\x123\n" +
	"\x15generated_conversions\x18\x0e \x01(\tR\x14generatedConversions\x12+\n" +
	"\x11responsive_images\x18\x0f \x01(\tR\x10responsiveImages\x12!\n" +
	"\forder_column\x18\x10 \x01(\x05R\vorderColumn\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\x03R\tupdatedAt\x12#\n" +
	"\rpresigned_url\x18\x13 \x01(\tR\fpresignedUrl\"\x86\x02\n" +
	"\x11UploadFileRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"model_type\x18\x05 \x01(\tR\tmodelType\x12\x19\n" +
	"\bmodel_id\x18\x06 \x01(\x03R\amodelId\x12'\n" +
	"\x0fcollection_name\x18\a \x01(\tR\x0ecollectionName\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x12\n" +
	"\x04disk\x18\t \x01(\tR\x04disk\"j\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.media.MediaR\x04data\"$\n" +
	"\x12GetFileByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"k\n" +
	"\x13GetFileByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.media.MediaR\x04data\"*\n" +
	"\x14GetFileByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"m\n" +
	"\x15GetFileByUUIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.media.MediaR\x04data\"\xaa\x01\n" +
	"\x16GetFilesByModelRequest\x12\x1d\n" +
	"\n" +
	"model_type\x18\x01 \x01(\tR\tmodelType\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\x03R\amodelId\x12'\n" +
	"\x0fcollection_name\x18\x03 \x01(\tR\x0ecollectionName\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x05 \x01(\x05R\aperPage\"}\n" +
	"\x17GetFilesByModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.media.GetFilesByModelDataR\x04data\"~\n" +
	"\x13GetFilesByModelData\x12\"\n" +
	"\x05media\x18\x01 \x03(\v2\f.media.MediaR\x05media\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x11GetFileURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eexpiry_seconds\x18\x02 \x01(\x05R\rexpirySeconds\"s\n" +
	"\x12GetFileURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.media.GetFileURLDataR\x04data\"A\n" +
	"\x0eGetFileURLData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x8b\x01\n" +
	"\x12GetAllMediaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1d\n" +
	"\n" +
	"model_type\x18\x03 \x01(\tR\tmodelType\x12'\n" +
	"\x0fcollection_name\x18\x04 \x01(\tR\x0ecollectionName\"u\n" +
	"\x13GetAllMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.media.GetAllMediaDataR\x04data\"z\n" +
	"\x0fGetAllMediaData\x12\"\n" +
	"\x05media\x18\x01 \x03(\v2\f.media.MediaR\x05media\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage2\x8f\x04\n" +
	"\fMediaService\x12C\n" +
	"\n" +
	"UploadFile\x12\x18.media.UploadFileRequest\x1a\x19.media.UploadFileResponse\"\x00\x12F\n" +
	"\vGetFileByID\x12\x19.media.GetFileByIDRequest\x1a\x1a.media.GetFileByIDResponse\"\x00\x12L\n" +
	"\rGetFileByUUID\x12\x1b.media.GetFileByUUIDRequest\x1a\x1c.media.GetFileByUUIDResponse\"\x00\x12R\n" +
	"\x0fGetFilesByModel\x12\x1d.media.GetFilesByModelRequest\x1a\x1e.media.GetFilesByModelResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteFile\x12\x18.media.DeleteFileRequest\x1a\x19.media.DeleteFileResponse\"\x00\x12C\n" +
	"\n" +
	"GetFileURL\x12\x18.media.GetFileURLRequest\x1a\x19.media.GetFileURLResponse\"\x00\x12F\n" +
	"\vGetAllMedia\x12\x19.media.GetAllMediaRequest\x1a\x1a.media.GetAllMediaResponse\"\x00B\x1aZ\x18shared/proto/media;mediab\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_media_proto_goTypes = []any{
	(*Media)(nil),                   // 0: media.Media
	(*UploadFileRequest)(nil),       // 1: media.UploadFileRequest
	(*UploadFileResponse)(nil),      // 2: media.UploadFileResponse
	(*GetFileByIDRequest)(nil),      // 3: media.GetFileByIDRequest
	(*GetFileByIDResponse)(nil),     // 4: media.GetFileByIDResponse
	(*GetFileByUUIDRequest)(nil),    // 5: media.GetFileByUUIDRequest
	(*GetFileByUUIDResponse)(nil),   // 6: media.GetFileByUUIDResponse
	(*GetFilesByModelRequest)(nil),  // 7: media.GetFilesByModelRequest
	(*GetFilesByModelResponse)(nil), // 8: media.GetFilesByModelResponse
	(*GetFilesByModelData)(nil),     // 9: media.GetFilesByModelData
	(*DeleteFileRequest)(nil),       // 10: media.DeleteFileRequest
	(*DeleteFileResponse)(nil),      // 11: media.DeleteFileResponse
	(*GetFileURLRequest)(nil),       // 12: media.GetFileURLRequest
	(*GetFileURLResponse)(nil),      // 13: media.GetFileURLResponse
	(*GetFileURLData)(nil),          // 14: media.GetFileURLData
	(*GetAllMediaRequest)(nil),      // 15: media.GetAllMediaRequest
	(*GetAllMediaResponse)(nil),     // 16: media.GetAllMediaResponse
	(*GetAllMediaData)(nil),         // 17: media.GetAllMediaData
}
var file_media_proto_depIdxs = []int32{
	0,  // 0: media.UploadFileResponse.data:type_name -> media.Media
	0,  // 1: media.GetFileByIDResponse.data:type_name -> media.Media
	0,  // 2: media.GetFileByUUIDResponse.data:type_name -> media.Media
	9,  // 3: media.GetFilesByModelResponse.data:type_name -> media.GetFilesByModelData
	0,  // 4: media.GetFilesByModelData.media:type_name -> media.Media
	14, // 5: media.GetFileURLResponse.data:type_name -> media.GetFileURLData
	17, // 6: media.GetAllMediaResponse.data:type_name -> media.GetAllMediaData
	0,  // 7: media.GetAllMediaData.media:type_name -> media.Media
	1,  // 8: media.MediaService.UploadFile:input_type -> media.UploadFileRequest
	3,  // 9: media.MediaService.GetFileByID:input_type -> media.GetFileByIDRequest
	5,  // 10: media.MediaService.GetFileByUUID:input_type -> media.GetFileByUUIDRequest
	7,  // 11: media.MediaService.GetFilesByModel:input_type -> media.GetFilesByModelRequest
	10, // 12: media.MediaService.DeleteFile:input_type -> media.DeleteFileRequest
	12, // 13: media.MediaService.GetFileURL:input_type -> media.GetFileURLRequest
	15, // 14: media.MediaService.GetAllMedia:input_type -> media.GetAllMediaRequest
	2,  // 15: media.MediaService.UploadFile:output_type -> media.UploadFileResponse
	4,  // 16: media.MediaService.GetFileByID:output_type -> media.GetFileByIDResponse
	6,  // 17: media.MediaService.GetFileByUUID:output_type -> media.GetFileByUUIDResponse
	8,  // 18: media.MediaService.GetFilesByModel:output_type -> media.GetFilesByModelResponse
	11, // 19: media.MediaService.DeleteFile:output_type -> media.DeleteFileResponse
	13, // 20: media.MediaService.GetFileURL:output_type -> media.GetFileURLResponse
	16, // 21: media.MediaService.GetAllMedia:output_type -> media.GetAllMediaResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
