/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkspaceRouteImport } from './routes/_layout/workspace'
import { Route as LayoutPricingRouteImport } from './routes/_layout/pricing'
import { Route as LayoutFeaturesRouteImport } from './routes/_layout/features'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutBlogRouteImport } from './routes/_layout/blog'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/admin/workspaces/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPlansIndexRouteImport } from './routes/admin/plans/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/admin/permissions/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogCategoriesIndexRouteImport } from './routes/admin/blog-categories/index'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as LayoutBlogIndexRouteImport } from './routes/_layout/blog/index'
import { Route as AdminWorkspacesCreateRouteImport } from './routes/admin/workspaces/create'
import { Route as AdminRolesCreateRouteImport } from './routes/admin/roles/create'
import { Route as AdminProductsCreateRouteImport } from './routes/admin/products/create'
import { Route as AdminPlansCreateRouteImport } from './routes/admin/plans/create'
import { Route as AdminPermissionsCreateRouteImport } from './routes/admin/permissions/create'
import { Route as AdminDiscountsCreateRouteImport } from './routes/admin/discounts/create'
import { Route as AdminBlogCreateRouteImport } from './routes/admin/blog/create'
import { Route as AdminBlogCategoriesCreateRouteImport } from './routes/admin/blog-categories/create'
import { Route as AdminAnnouncementsCreateRouteImport } from './routes/admin/announcements/create'
import { Route as LayoutBlogSlugRouteImport } from './routes/_layout/blog/$slug'
import { Route as AdminWorkspacesIdIndexRouteImport } from './routes/admin/workspaces/$id/index'
import { Route as AdminRolesIdIndexRouteImport } from './routes/admin/roles/$id/index'
import { Route as AdminProductsIdIndexRouteImport } from './routes/admin/products/$id/index'
import { Route as AdminPlansIdIndexRouteImport } from './routes/admin/plans/$id/index'
import { Route as AdminPermissionsIdIndexRouteImport } from './routes/admin/permissions/$id/index'
import { Route as AdminDiscountsIdIndexRouteImport } from './routes/admin/discounts/$id/index'
import { Route as AdminBlogIdIndexRouteImport } from './routes/admin/blog/$id/index'
import { Route as AdminBlogCategoriesIdIndexRouteImport } from './routes/admin/blog-categories/$id/index'
import { Route as AdminAnnouncementsIdIndexRouteImport } from './routes/admin/announcements/$id/index'
import { Route as AdminWorkspacesIdEditRouteImport } from './routes/admin/workspaces/$id/edit'
import { Route as AdminRolesIdPermissionsRouteImport } from './routes/admin/roles/$id/permissions'
import { Route as AdminRolesIdEditRouteImport } from './routes/admin/roles/$id/edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id/edit'
import { Route as AdminPlansIdEditRouteImport } from './routes/admin/plans/$id/edit'
import { Route as AdminPermissionsIdEditRouteImport } from './routes/admin/permissions/$id/edit'
import { Route as AdminDiscountsIdEditRouteImport } from './routes/admin/discounts/$id/edit'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin/blog/$id/edit'
import { Route as AdminBlogCategoriesIdEditRouteImport } from './routes/admin/blog-categories/$id/edit'
import { Route as AdminAnnouncementsIdEditRouteImport } from './routes/admin/announcements/$id/edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkspaceRoute = LayoutWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPricingRoute = LayoutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeaturesRoute = LayoutFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesIndexRoute =
  AdminBlogCategoriesIndexRouteImport.update({
    id: '/blog-categories/',
    path: '/blog-categories/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutBlogIndexRoute = LayoutBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutBlogRoute,
} as any)
const AdminWorkspacesCreateRoute = AdminWorkspacesCreateRouteImport.update({
  id: '/workspaces/create',
  path: '/workspaces/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesCreateRoute = AdminRolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansCreateRoute = AdminPlansCreateRouteImport.update({
  id: '/plans/create',
  path: '/plans/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsCreateRoute = AdminPermissionsCreateRouteImport.update({
  id: '/permissions/create',
  path: '/permissions/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsCreateRoute = AdminDiscountsCreateRouteImport.update({
  id: '/discounts/create',
  path: '/discounts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCreateRoute = AdminBlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesCreateRoute =
  AdminBlogCategoriesCreateRouteImport.update({
    id: '/blog-categories/create',
    path: '/blog-categories/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsCreateRoute =
  AdminAnnouncementsCreateRouteImport.update({
    id: '/announcements/create',
    path: '/announcements/create',
    getParentRoute: () => AdminRoute,
  } as any)
const LayoutBlogSlugRoute = LayoutBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutBlogRoute,
} as any)
const AdminWorkspacesIdIndexRoute = AdminWorkspacesIdIndexRouteImport.update({
  id: '/workspaces/$id/',
  path: '/workspaces/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIdIndexRoute = AdminRolesIdIndexRouteImport.update({
  id: '/roles/$id/',
  path: '/roles/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdIndexRoute = AdminProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIdIndexRoute = AdminPlansIdIndexRouteImport.update({
  id: '/plans/$id/',
  path: '/plans/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIdIndexRoute = AdminPermissionsIdIndexRouteImport.update({
  id: '/permissions/$id/',
  path: '/permissions/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIdIndexRoute = AdminDiscountsIdIndexRouteImport.update({
  id: '/discounts/$id/',
  path: '/discounts/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdIndexRoute = AdminBlogIdIndexRouteImport.update({
  id: '/blog/$id/',
  path: '/blog/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesIdIndexRoute =
  AdminBlogCategoriesIdIndexRouteImport.update({
    id: '/blog-categories/$id/',
    path: '/blog-categories/$id/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsIdIndexRoute =
  AdminAnnouncementsIdIndexRouteImport.update({
    id: '/announcements/$id/',
    path: '/announcements/$id/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWorkspacesIdEditRoute = AdminWorkspacesIdEditRouteImport.update({
  id: '/workspaces/$id/edit',
  path: '/workspaces/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIdPermissionsRoute = AdminRolesIdPermissionsRouteImport.update({
  id: '/roles/$id/permissions',
  path: '/roles/$id/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIdEditRoute = AdminRolesIdEditRouteImport.update({
  id: '/roles/$id/edit',
  path: '/roles/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIdEditRoute = AdminPlansIdEditRouteImport.update({
  id: '/plans/$id/edit',
  path: '/plans/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIdEditRoute = AdminPermissionsIdEditRouteImport.update({
  id: '/permissions/$id/edit',
  path: '/permissions/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIdEditRoute = AdminDiscountsIdEditRouteImport.update({
  id: '/discounts/$id/edit',
  path: '/discounts/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesIdEditRoute =
  AdminBlogCategoriesIdEditRouteImport.update({
    id: '/blog-categories/$id/edit',
    path: '/blog-categories/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsIdEditRoute =
  AdminAnnouncementsIdEditRouteImport.update({
    id: '/announcements/$id/edit',
    path: '/announcements/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog': typeof LayoutBlogRouteWithChildren
  '/contact': typeof LayoutContactRoute
  '/features': typeof LayoutFeaturesRoute
  '/pricing': typeof LayoutPricingRoute
  '/workspace': typeof LayoutWorkspaceRoute
  '/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/blog-categories/create': typeof AdminBlogCategoriesCreateRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/permissions/create': typeof AdminPermissionsCreateRoute
  '/admin/plans/create': typeof AdminPlansCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/roles/create': typeof AdminRolesCreateRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/blog/': typeof LayoutBlogIndexRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/permissions': typeof AdminPermissionsIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/admin/announcements/$id/edit': typeof AdminAnnouncementsIdEditRoute
  '/admin/blog-categories/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/discounts/$id/edit': typeof AdminDiscountsIdEditRoute
  '/admin/permissions/$id/edit': typeof AdminPermissionsIdEditRoute
  '/admin/plans/$id/edit': typeof AdminPlansIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/roles/$id/permissions': typeof AdminRolesIdPermissionsRoute
  '/admin/workspaces/$id/edit': typeof AdminWorkspacesIdEditRoute
  '/admin/announcements/$id': typeof AdminAnnouncementsIdIndexRoute
  '/admin/blog-categories/$id': typeof AdminBlogCategoriesIdIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdIndexRoute
  '/admin/discounts/$id': typeof AdminDiscountsIdIndexRoute
  '/admin/permissions/$id': typeof AdminPermissionsIdIndexRoute
  '/admin/plans/$id': typeof AdminPlansIdIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
  '/admin/roles/$id': typeof AdminRolesIdIndexRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contact': typeof LayoutContactRoute
  '/features': typeof LayoutFeaturesRoute
  '/pricing': typeof LayoutPricingRoute
  '/workspace': typeof LayoutWorkspaceRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/blog-categories/create': typeof AdminBlogCategoriesCreateRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/permissions/create': typeof AdminPermissionsCreateRoute
  '/admin/plans/create': typeof AdminPlansCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/roles/create': typeof AdminRolesCreateRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/permissions': typeof AdminPermissionsIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/admin/announcements/$id/edit': typeof AdminAnnouncementsIdEditRoute
  '/admin/blog-categories/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/discounts/$id/edit': typeof AdminDiscountsIdEditRoute
  '/admin/permissions/$id/edit': typeof AdminPermissionsIdEditRoute
  '/admin/plans/$id/edit': typeof AdminPlansIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/roles/$id/permissions': typeof AdminRolesIdPermissionsRoute
  '/admin/workspaces/$id/edit': typeof AdminWorkspacesIdEditRoute
  '/admin/announcements/$id': typeof AdminAnnouncementsIdIndexRoute
  '/admin/blog-categories/$id': typeof AdminBlogCategoriesIdIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdIndexRoute
  '/admin/discounts/$id': typeof AdminDiscountsIdIndexRoute
  '/admin/permissions/$id': typeof AdminPermissionsIdIndexRoute
  '/admin/plans/$id': typeof AdminPlansIdIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
  '/admin/roles/$id': typeof AdminRolesIdIndexRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/blog': typeof LayoutBlogRouteWithChildren
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/features': typeof LayoutFeaturesRoute
  '/_layout/pricing': typeof LayoutPricingRoute
  '/_layout/workspace': typeof LayoutWorkspaceRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_layout/blog/$slug': typeof LayoutBlogSlugRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/blog-categories/create': typeof AdminBlogCategoriesCreateRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/permissions/create': typeof AdminPermissionsCreateRoute
  '/admin/plans/create': typeof AdminPlansCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/roles/create': typeof AdminRolesCreateRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/_layout/blog/': typeof LayoutBlogIndexRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/blog-categories/': typeof AdminBlogCategoriesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/permissions/': typeof AdminPermissionsIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/admin/announcements/$id/edit': typeof AdminAnnouncementsIdEditRoute
  '/admin/blog-categories/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/discounts/$id/edit': typeof AdminDiscountsIdEditRoute
  '/admin/permissions/$id/edit': typeof AdminPermissionsIdEditRoute
  '/admin/plans/$id/edit': typeof AdminPlansIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/roles/$id/permissions': typeof AdminRolesIdPermissionsRoute
  '/admin/workspaces/$id/edit': typeof AdminWorkspacesIdEditRoute
  '/admin/announcements/$id/': typeof AdminAnnouncementsIdIndexRoute
  '/admin/blog-categories/$id/': typeof AdminBlogCategoriesIdIndexRoute
  '/admin/blog/$id/': typeof AdminBlogIdIndexRoute
  '/admin/discounts/$id/': typeof AdminDiscountsIdIndexRoute
  '/admin/permissions/$id/': typeof AdminPermissionsIdIndexRoute
  '/admin/plans/$id/': typeof AdminPlansIdIndexRoute
  '/admin/products/$id/': typeof AdminProductsIdIndexRoute
  '/admin/roles/$id/': typeof AdminRolesIdIndexRoute
  '/admin/workspaces/$id/': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/blog'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/workspace'
    | '/'
    | '/admin/'
    | '/blog/$slug'
    | '/admin/announcements/create'
    | '/admin/blog-categories/create'
    | '/admin/blog/create'
    | '/admin/discounts/create'
    | '/admin/permissions/create'
    | '/admin/plans/create'
    | '/admin/products/create'
    | '/admin/roles/create'
    | '/admin/workspaces/create'
    | '/blog/'
    | '/admin/announcements'
    | '/admin/blog-categories'
    | '/admin/blog'
    | '/admin/discounts'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workspaces'
    | '/admin/announcements/$id/edit'
    | '/admin/blog-categories/$id/edit'
    | '/admin/blog/$id/edit'
    | '/admin/discounts/$id/edit'
    | '/admin/permissions/$id/edit'
    | '/admin/plans/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/roles/$id/permissions'
    | '/admin/workspaces/$id/edit'
    | '/admin/announcements/$id'
    | '/admin/blog-categories/$id'
    | '/admin/blog/$id'
    | '/admin/discounts/$id'
    | '/admin/permissions/$id'
    | '/admin/plans/$id'
    | '/admin/products/$id'
    | '/admin/roles/$id'
    | '/admin/workspaces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/workspace'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/admin/announcements/create'
    | '/admin/blog-categories/create'
    | '/admin/blog/create'
    | '/admin/discounts/create'
    | '/admin/permissions/create'
    | '/admin/plans/create'
    | '/admin/products/create'
    | '/admin/roles/create'
    | '/admin/workspaces/create'
    | '/blog'
    | '/admin/announcements'
    | '/admin/blog-categories'
    | '/admin/blog'
    | '/admin/discounts'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workspaces'
    | '/admin/announcements/$id/edit'
    | '/admin/blog-categories/$id/edit'
    | '/admin/blog/$id/edit'
    | '/admin/discounts/$id/edit'
    | '/admin/permissions/$id/edit'
    | '/admin/plans/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/roles/$id/permissions'
    | '/admin/workspaces/$id/edit'
    | '/admin/announcements/$id'
    | '/admin/blog-categories/$id'
    | '/admin/blog/$id'
    | '/admin/discounts/$id'
    | '/admin/permissions/$id'
    | '/admin/plans/$id'
    | '/admin/products/$id'
    | '/admin/roles/$id'
    | '/admin/workspaces/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/_layout/blog'
    | '/_layout/contact'
    | '/_layout/features'
    | '/_layout/pricing'
    | '/_layout/workspace'
    | '/_layout/'
    | '/admin/'
    | '/_layout/blog/$slug'
    | '/admin/announcements/create'
    | '/admin/blog-categories/create'
    | '/admin/blog/create'
    | '/admin/discounts/create'
    | '/admin/permissions/create'
    | '/admin/plans/create'
    | '/admin/products/create'
    | '/admin/roles/create'
    | '/admin/workspaces/create'
    | '/_layout/blog/'
    | '/admin/announcements/'
    | '/admin/blog-categories/'
    | '/admin/blog/'
    | '/admin/discounts/'
    | '/admin/permissions/'
    | '/admin/plans/'
    | '/admin/products/'
    | '/admin/profile/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/admin/workspaces/'
    | '/admin/announcements/$id/edit'
    | '/admin/blog-categories/$id/edit'
    | '/admin/blog/$id/edit'
    | '/admin/discounts/$id/edit'
    | '/admin/permissions/$id/edit'
    | '/admin/plans/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/roles/$id/permissions'
    | '/admin/workspaces/$id/edit'
    | '/admin/announcements/$id/'
    | '/admin/blog-categories/$id/'
    | '/admin/blog/$id/'
    | '/admin/discounts/$id/'
    | '/admin/permissions/$id/'
    | '/admin/plans/$id/'
    | '/admin/products/$id/'
    | '/admin/roles/$id/'
    | '/admin/workspaces/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workspace': {
      id: '/_layout/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof LayoutWorkspaceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pricing': {
      id: '/_layout/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LayoutPricingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/features': {
      id: '/_layout/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof LayoutFeaturesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/': {
      id: '/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions/': {
      id: '/admin/permissions/'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories/': {
      id: '/admin/blog-categories/'
      path: '/blog-categories'
      fullPath: '/admin/blog-categories'
      preLoaderRoute: typeof AdminBlogCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/blog/': {
      id: '/_layout/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof LayoutBlogIndexRouteImport
      parentRoute: typeof LayoutBlogRoute
    }
    '/admin/workspaces/create': {
      id: '/admin/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/admin/workspaces/create'
      preLoaderRoute: typeof AdminWorkspacesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/create': {
      id: '/admin/roles/create'
      path: '/roles/create'
      fullPath: '/admin/roles/create'
      preLoaderRoute: typeof AdminRolesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/create': {
      id: '/admin/plans/create'
      path: '/plans/create'
      fullPath: '/admin/plans/create'
      preLoaderRoute: typeof AdminPlansCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions/create': {
      id: '/admin/permissions/create'
      path: '/permissions/create'
      fullPath: '/admin/permissions/create'
      preLoaderRoute: typeof AdminPermissionsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/create': {
      id: '/admin/discounts/create'
      path: '/discounts/create'
      fullPath: '/admin/discounts/create'
      preLoaderRoute: typeof AdminDiscountsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/create': {
      id: '/admin/blog/create'
      path: '/blog/create'
      fullPath: '/admin/blog/create'
      preLoaderRoute: typeof AdminBlogCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories/create': {
      id: '/admin/blog-categories/create'
      path: '/blog-categories/create'
      fullPath: '/admin/blog-categories/create'
      preLoaderRoute: typeof AdminBlogCategoriesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/create': {
      id: '/admin/announcements/create'
      path: '/announcements/create'
      fullPath: '/admin/announcements/create'
      preLoaderRoute: typeof AdminAnnouncementsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/blog/$slug': {
      id: '/_layout/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof LayoutBlogSlugRouteImport
      parentRoute: typeof LayoutBlogRoute
    }
    '/admin/workspaces/$id/': {
      id: '/admin/workspaces/$id/'
      path: '/workspaces/$id'
      fullPath: '/admin/workspaces/$id'
      preLoaderRoute: typeof AdminWorkspacesIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/$id/': {
      id: '/admin/roles/$id/'
      path: '/roles/$id'
      fullPath: '/admin/roles/$id'
      preLoaderRoute: typeof AdminRolesIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id/': {
      id: '/admin/products/$id/'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/$id/': {
      id: '/admin/plans/$id/'
      path: '/plans/$id'
      fullPath: '/admin/plans/$id'
      preLoaderRoute: typeof AdminPlansIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions/$id/': {
      id: '/admin/permissions/$id/'
      path: '/permissions/$id'
      fullPath: '/admin/permissions/$id'
      preLoaderRoute: typeof AdminPermissionsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/$id/': {
      id: '/admin/discounts/$id/'
      path: '/discounts/$id'
      fullPath: '/admin/discounts/$id'
      preLoaderRoute: typeof AdminDiscountsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id/': {
      id: '/admin/blog/$id/'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories/$id/': {
      id: '/admin/blog-categories/$id/'
      path: '/blog-categories/$id'
      fullPath: '/admin/blog-categories/$id'
      preLoaderRoute: typeof AdminBlogCategoriesIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/$id/': {
      id: '/admin/announcements/$id/'
      path: '/announcements/$id'
      fullPath: '/admin/announcements/$id'
      preLoaderRoute: typeof AdminAnnouncementsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$id/edit': {
      id: '/admin/workspaces/$id/edit'
      path: '/workspaces/$id/edit'
      fullPath: '/admin/workspaces/$id/edit'
      preLoaderRoute: typeof AdminWorkspacesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/$id/permissions': {
      id: '/admin/roles/$id/permissions'
      path: '/roles/$id/permissions'
      fullPath: '/admin/roles/$id/permissions'
      preLoaderRoute: typeof AdminRolesIdPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/$id/edit': {
      id: '/admin/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/admin/roles/$id/edit'
      preLoaderRoute: typeof AdminRolesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans/$id/edit': {
      id: '/admin/plans/$id/edit'
      path: '/plans/$id/edit'
      fullPath: '/admin/plans/$id/edit'
      preLoaderRoute: typeof AdminPlansIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions/$id/edit': {
      id: '/admin/permissions/$id/edit'
      path: '/permissions/$id/edit'
      fullPath: '/admin/permissions/$id/edit'
      preLoaderRoute: typeof AdminPermissionsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/$id/edit': {
      id: '/admin/discounts/$id/edit'
      path: '/discounts/$id/edit'
      fullPath: '/admin/discounts/$id/edit'
      preLoaderRoute: typeof AdminDiscountsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories/$id/edit': {
      id: '/admin/blog-categories/$id/edit'
      path: '/blog-categories/$id/edit'
      fullPath: '/admin/blog-categories/$id/edit'
      preLoaderRoute: typeof AdminBlogCategoriesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/$id/edit': {
      id: '/admin/announcements/$id/edit'
      path: '/announcements/$id/edit'
      fullPath: '/admin/announcements/$id/edit'
      preLoaderRoute: typeof AdminAnnouncementsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface LayoutBlogRouteChildren {
  LayoutBlogSlugRoute: typeof LayoutBlogSlugRoute
  LayoutBlogIndexRoute: typeof LayoutBlogIndexRoute
}

const LayoutBlogRouteChildren: LayoutBlogRouteChildren = {
  LayoutBlogSlugRoute: LayoutBlogSlugRoute,
  LayoutBlogIndexRoute: LayoutBlogIndexRoute,
}

const LayoutBlogRouteWithChildren = LayoutBlogRoute._addFileChildren(
  LayoutBlogRouteChildren,
)

interface LayoutRouteChildren {
  LayoutBlogRoute: typeof LayoutBlogRouteWithChildren
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutFeaturesRoute: typeof LayoutFeaturesRoute
  LayoutPricingRoute: typeof LayoutPricingRoute
  LayoutWorkspaceRoute: typeof LayoutWorkspaceRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlogRoute: LayoutBlogRouteWithChildren,
  LayoutContactRoute: LayoutContactRoute,
  LayoutFeaturesRoute: LayoutFeaturesRoute,
  LayoutPricingRoute: LayoutPricingRoute,
  LayoutWorkspaceRoute: LayoutWorkspaceRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnnouncementsCreateRoute: typeof AdminAnnouncementsCreateRoute
  AdminBlogCategoriesCreateRoute: typeof AdminBlogCategoriesCreateRoute
  AdminBlogCreateRoute: typeof AdminBlogCreateRoute
  AdminDiscountsCreateRoute: typeof AdminDiscountsCreateRoute
  AdminPermissionsCreateRoute: typeof AdminPermissionsCreateRoute
  AdminPlansCreateRoute: typeof AdminPlansCreateRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminRolesCreateRoute: typeof AdminRolesCreateRoute
  AdminWorkspacesCreateRoute: typeof AdminWorkspacesCreateRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminBlogCategoriesIndexRoute: typeof AdminBlogCategoriesIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
  AdminAnnouncementsIdEditRoute: typeof AdminAnnouncementsIdEditRoute
  AdminBlogCategoriesIdEditRoute: typeof AdminBlogCategoriesIdEditRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
  AdminDiscountsIdEditRoute: typeof AdminDiscountsIdEditRoute
  AdminPermissionsIdEditRoute: typeof AdminPermissionsIdEditRoute
  AdminPlansIdEditRoute: typeof AdminPlansIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminRolesIdEditRoute: typeof AdminRolesIdEditRoute
  AdminRolesIdPermissionsRoute: typeof AdminRolesIdPermissionsRoute
  AdminWorkspacesIdEditRoute: typeof AdminWorkspacesIdEditRoute
  AdminAnnouncementsIdIndexRoute: typeof AdminAnnouncementsIdIndexRoute
  AdminBlogCategoriesIdIndexRoute: typeof AdminBlogCategoriesIdIndexRoute
  AdminBlogIdIndexRoute: typeof AdminBlogIdIndexRoute
  AdminDiscountsIdIndexRoute: typeof AdminDiscountsIdIndexRoute
  AdminPermissionsIdIndexRoute: typeof AdminPermissionsIdIndexRoute
  AdminPlansIdIndexRoute: typeof AdminPlansIdIndexRoute
  AdminProductsIdIndexRoute: typeof AdminProductsIdIndexRoute
  AdminRolesIdIndexRoute: typeof AdminRolesIdIndexRoute
  AdminWorkspacesIdIndexRoute: typeof AdminWorkspacesIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnnouncementsCreateRoute: AdminAnnouncementsCreateRoute,
  AdminBlogCategoriesCreateRoute: AdminBlogCategoriesCreateRoute,
  AdminBlogCreateRoute: AdminBlogCreateRoute,
  AdminDiscountsCreateRoute: AdminDiscountsCreateRoute,
  AdminPermissionsCreateRoute: AdminPermissionsCreateRoute,
  AdminPlansCreateRoute: AdminPlansCreateRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminRolesCreateRoute: AdminRolesCreateRoute,
  AdminWorkspacesCreateRoute: AdminWorkspacesCreateRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminBlogCategoriesIndexRoute: AdminBlogCategoriesIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
  AdminAnnouncementsIdEditRoute: AdminAnnouncementsIdEditRoute,
  AdminBlogCategoriesIdEditRoute: AdminBlogCategoriesIdEditRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
  AdminDiscountsIdEditRoute: AdminDiscountsIdEditRoute,
  AdminPermissionsIdEditRoute: AdminPermissionsIdEditRoute,
  AdminPlansIdEditRoute: AdminPlansIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminRolesIdEditRoute: AdminRolesIdEditRoute,
  AdminRolesIdPermissionsRoute: AdminRolesIdPermissionsRoute,
  AdminWorkspacesIdEditRoute: AdminWorkspacesIdEditRoute,
  AdminAnnouncementsIdIndexRoute: AdminAnnouncementsIdIndexRoute,
  AdminBlogCategoriesIdIndexRoute: AdminBlogCategoriesIdIndexRoute,
  AdminBlogIdIndexRoute: AdminBlogIdIndexRoute,
  AdminDiscountsIdIndexRoute: AdminDiscountsIdIndexRoute,
  AdminPermissionsIdIndexRoute: AdminPermissionsIdIndexRoute,
  AdminPlansIdIndexRoute: AdminPlansIdIndexRoute,
  AdminProductsIdIndexRoute: AdminProductsIdIndexRoute,
  AdminRolesIdIndexRoute: AdminRolesIdIndexRoute,
  AdminWorkspacesIdIndexRoute: AdminWorkspacesIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
